---
  - name: Database
    shell: RAILS_ENV=production bundle exec rake db:migrate
    args:
      chdir: "{{ redmine }}"

  - name: dataset
    shell: RAILS_ENV=production REDMINE_LANG=en bundle exec rake redmine:load_default_data
    args:
      chdir: "{{ redmine }}"
