---
  - name: UPDATE
    apt:
      update_cache: yes

  - name: RELOAD
    systemd:
      name: daemon_reload=yes

  - name: NGINX START
    systemd:
      name: nginx
      state: started

  - name: NGINX RESTART
    systemd:
      name: nginx
      state: restarted
